Abstract and decrypt templates

diff --git a/templates/gpg.sh.j2 b/templates/gpg.sh.j2
--- a/templates/gpg.sh.j2
+++ b/templates/gpg.sh.j2
@@ -1,26 +1,22 @@
-$ANSIBLE_VAULT;1.1;AES256
-32343534643165643433333465326437616263623865626164313765313935636366303638346239
-3565663963663264373530346163663638396565636432370a313631336136333661313963626361
-62616261653563626562646466653630343039396231646431383665333763626535383963333366
-3531376534376164350a326133623264366666363466643264353161313038316430373732666162
-36323265363762383164343632333332386236373838356638313536623532643132306139356639
-37336162633230396132366637623235363139633935663438656339303762306432613834376333
-37663738346365653564306364333162653937636634353266623166653364346335393338373236
-63353134636431323337356239613239383262393434323830323064346536643233646539353533
-34323266353637336138313965343662623566313762323337633037643132386439393261636338
-39626266663634613162643565383763396232313166306537336461363633346162343263656239
-61376639306533316665376163396138373336393963353839343635643738633636383361633462
-63303663383966333262326334633539373166653232643562653338623730656433373464633237
-34363362663533313035663539396263613130633633656364336335333633663639666635303165
-39353339343334366632663231663438623931616430303436626138653962386233366432393766
-61616236643435333166626538666532636636343031323233643533313762356262306361353666
-36616133646337616363353839626430303530336666386534643761393530653531663238363361
-36323964323635626635356632316363623831653963643161633130643634333032393734343937
-32613531393235306336376164343739636366383863393663363539356130383835333831633534
-33313337363437623964356131343131386131353837666364323562383038356630303861323630
-64653366393938393363343761626433656236303063373534363331316265366165333965626436
-64373536643234636133383165623031323338316437343232346137623166396535353235626334
-36343462383265376166666231303263613063626466353233663431636534363735633137373839
-65303863663763383331353336363132663138643563303930336166356162633533383562326463
-61613031663534366433396437376239633937653036313562666464386337633239313834346634
-3662
+#!/bin/bash
+
+# Exit on error
+set -e
+# Treat unset variables as an error when substituting
+set -u
+
+# Look for input from tty
+export GPG_TTY=$(tty)
+
+gpg --batch --gen-key <<EOF
+  Key-Type: RSA
+  Key-Length: 4096
+  Key-Usage: cert,sign
+  Subkey-Type: RSA
+  Subkey-Length: 4096
+  Subkey-Usage: encrypt
+  Name-Real:
+  Name-Email:
+  Expire-Date: 0
+  Passphrase:
+EOF
